FROM php:7.4-fpm
RUN pecl install xdebug-2.8.1 && docker-php-ext-enable xdebug
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN cp -f /var/assets/config.inc.php /var/www/site/adm 
