FROM php:7.4-fpm
RUN pecl install xdebug-2.8.1 && docker-php-ext-enable xdebug
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

RUN addgroup --gid 1000 --system socketuser
RUN adduser --uid 1000 --system --ingroup socketuser socketuser
RUN rm /usr/local/etc/php-fpm.d/www.conf
RUN rm /usr/local/etc/php-fpm.d/zz-docker.conf

USER socketuser

CMD ["php-fpm", "--nodaemonize"]
